{% set version = "3.1" %}
{% set sha256 = "588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2" %}

package:
  name: gperf
  version: {{ version }}

source:
  fn: gperf-{{ version }}.tar.gz
  url: http://ftp.gnu.org/pub/gnu/gperf/gperf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f "${PREFIX}/bin/gperf"  # [unix]

about:
  home: https://www.gnu.org/software/gperf/
  license: GPL-3
  summary: 'GNU gperf is a perfect hash function generator.'

extra:
  recipe-maintainers:
    - tfors
    - mingwandroid
