travis:
  secure:
    BINSTAR_TOKEN: V2tsIg7gYJVcIM4wxmic1LIg/cenhtKR+tRFXgmwkmYE78qdSL6ZrCz7RAmlCOsKVZxFfiNVGgGzRRfsys6eLBfbIs9/LZEkXPh1pJjn8TIk6RftXuqHV0PP8Hw92Ik4wfM6sj2kpykQ4mHRTMEtp3ymZ/nu8uNMgiK5wR3TUc0J/t/2MYIuDEAMTLFFYQ/DOhlKvP3RzqJmx/2numC9zPTB3RhwO7y+i3a9k7Wbr1ePdLSkoH2yC1d+kDrlSnwXOiZoVr5ozz41J5j26mjW/KrfZR/1mMxtahN94qd0PuKn6H++fP4+mXwewq31cC5QBbCH7T60HLXU9bzAStCStNgeVp2ltViUYr222NlxOIRvWkqFvgQb+lYDU4ud/eqwEiZ4ZFBUlSBbeBtzVrprt6py1/AfnFdSEoy3WP54KcUy0z58qd0Mr5tE4D+8dKmauCwGctND8/fj4E6eNnu94/bM/Xli6ILuaP/ixCzQSYMCGvV3HB2q6gJQHnV+SuEKKa3OuGmCvFN4dEP8xGqzlM6I1iyIbCE5Rhj0F3IhzVmvrVfTw5bMHnKuxFrB61VUqNzPkTAjELA2Mym+CKa6plt0v0db9bXGBblzcFoxK+BT0ab+RkTcRzzEEo5e4LJQ7JE9qV+3sigDqnXK/DeAe1x8ZEyV23cslbz4872IjQk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
