travis:
  secure:
    BINSTAR_TOKEN: hcaw5SICRkGJ4xO4I8NwqNU6LRSc6u+hGCz2kV6ZFaY0t6Qm7kVbl+KRrpOEiL1cFbHj4Xcn4bNR+MjX+DHW64SyceZ91oCnq1qAUAGEbknvh19zWbp999+zk2heXZNozfgCKeZ78SKoF5zB82b18xpEPCHwoUpNupHO+nFpmxYvJLWuVgUfJoJdSnhQdChIX6zv3sMsL+uHUQkizQB3nAu4CJyuYABR/J3WqNgUgW6mLngMZWksDl/oilCmQfJoYJNFOywUvOL3iWec6keeXAJXj4HQvOeOcetHlNRRwU+JwIQIeeP2AjNQH7OxbYl7Hj86aIlSV8yUim7xQfENCQGVL0V0XwTKSQWwY3SZOPPiulaK6U5VleMBjPNaUJxnenjVxpr/LY7yVcS2/tsbLg8YiFd4ZcPsMrm+SBUUXJ4S0O49+UQvTdcLe8jpUc9Js7HQ6c+zYs/a5GWPuNcTMwY45IAbg0I7RJT3zShAYLDXY64GRKwifCWHXAB5t8KbDpF5FgVw79uLsbqfzGZ6jUg7UoUzpajK29iEtB+t0/75rDluG+fEQ09s/eIB7X+Mcy/dlSc+ST8Wm1AaX9shSCu3N03o3VmpQSJhLOjsfv9hzJ/8/Bk5iKypbllLHgF0wB/KyPKdVhL53DG8Xonj0OKmvrHTCOo11llfCwLZj0M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
